# Config CraftKeeperu

# Napojení na SQL
sql:
  hostname: host
  port: 3306
  database: database
  username: user
  password: password

# Nastavení SQL
settings:
  minimumConnections: 2
  maximumConnections: 5
  timout: 30000

# Integrace a zasílání exceptions na Sentry
sentry-dsn: ''

# CraftKeeper related nastaveni

debug: true

## Bude logovat SQL věci
debugSQL: true

## Bude logovat informace o block-breaku
debugBlockBreak: true

## Permission node, přes jaký bude CraftKeeper kontrolovat rank; x = písmeno ranku
permissionRankNode: craftprison.rank.x

## MONITOR, HIGHEST, HIGH, NORMAL, LOW, LOWEST
block-break-event-level: "NORMAL"

## True / False
drops-to-inv: true
exp-to-player: true
do-damage-to-tool: true

## AutoSell related nastavení
autosell:
  ## Čas mezi aktulizacemi, kdy plugin pošle uložené peníze do vaultu
  update-time: 30000
  cooldown:
    enabled: true
    ## Cooldown před tím, než hráč bude moct použít autosell znovu
    time: 360000
  duration:
    infinite: false
    ## Čas jak dlouho autosell poběží
    time: 120000
  permission-node: craftprison.autosell
  allow-in-creative: false
  disabled-worlds:
    - "worldName"

multipliers:
  ## Za kolik minut se budou ukládat všechny multipliery
  ## Pozor! Nikdy sem nedávej 0. Spamovalo by to každých 10s SQL.
  save-every-minute: 30
  ## Vypíše hráčovi všechny personal + global + event multipliery při připojení na server
  announce-active-multipliers-on-join: true
  personal:
    ## Vypíše zprávu, že hráčovi začal personal mutliplier
    message-on-start: true
    ## Vypíše zprávu, že hráčovi vypršel personal multiplier
    message-on-end: true
  global:
    ## Vypíše zprávu všem hráčům, že začal global multiplier
    message-on-start: true
    ## Vypíše zprávu všem hráčům, že skončil global multiplier
    message-on-end: true
  event:
    message-on-end: true
    message-on-start: true