# Config CraftKeeperu

# Napojení na SQL
sql:
  hostname: host
  port: 3306
  database: database
  username: user
  password: password

# Nastavení SQL
settings:
  minimumConnections: 2
  maximumConnections: 5
  timout: 30000

# Integrace a zasílání exceptions na Sentry
sentry-dsn: ''

# CraftKeeper related nastaveni

debug: true

## Bude logovat SQL věci
debugSQL: true

## Bude logovat informace o block-breaku
debugBlockBreak: true

## Permission node, přes jaký bude CraftKeeper kontrolovat rank; x = číslo ranku
permissionRankNode: craftprison.rank.x

## MONITOR, HIGHEST, HIGH, NORMAL, LOW, LOWEST
block-break-event-level: "NORMAL"

## AutoSell related nastavení
autosell:
  ## Čas mezi aktulizacemi, kdy plugin pošle uložené peníze do vaultu
  update-time: 30000
  cooldown:
    enabled: true
    ## Cooldown před tím, než hráč bude moct použít autosell znovu
    time: 360000
  duration:
    infinite: false
    ## Čas jak dlouho autosell poběží
    time: 120000
  permission-node: craftprison.autosell
  do-damage-to-tool: true
  allow-in-creative: false
  exp-to-player: true
  disabled-worlds:
    - "worldName"