name: CraftKeeper
version: 1.0.0
description: Autosell plugin pro Prison server s Multipliery
depend:
  - "CraftEconomy"
  - "CraftPrison"
  - "Minepacks"
author: lilmayu
api-version: 1.16
main: cz.craftmania.craftkeeper.Main
